### ISSUE TITLE
Problem with image in Actor sheet.

### ISSUE THREAD

**Issue by Damaskian** [CurtR95/FVTT-Dishonored#88] opened 2021-01-31 20:07 UTC
Hi! :D 
When adding a photo to the sheet of a player and non-player character. It is not saved. Once the picture is chosen, when you press F5 or refresh Foundry, the outsider's mark is set by default. 🤔
I have tried creating a new world without modules and the problem persists.

Browser: Client Foundry VTT
Modules Installed: 0
Steps for Reproduction: Create Actor, add image, and when you hit F5, it is removed.
Expected Behaviour: The selected image is kept.
Actual Behaviour: The chosen image is replaced by the outsider's mark.
Screenshot (if possible):

**Comment by CurtR95** [comment] 2021-01-31 20:24
@Damaskian actually this is partially related to a bug Foundry has at the moment (#79). Having said that, this is likely caused by the fix being too over egregious. I'll try and get this fixed in the next release, but that might take a while yet... Thanks for letting me know!

**Comment by Damaskian** [comment] 2021-01-31 20:29
Great! No rush. My players will fall into the void with or without an image. 😈

**Closed** 2021-04-30 13:41 UTC
Labels: P1, bug
